modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="almet"
version="1.3.0"
displayName="Almet Vikast"
credits="TheFatRat Arcadia"
displayURL="https://mcreator.net"
authors="Alezinha"

[[dependencies.almet]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.almet]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

